---
kafka:
  hosts:
    - 127.0.0.1:9093
  adminUsername: admin
  adminPassword: password
  username: user
  password: password
  topicName: test-topic
  partitions: 1
  replicas: 1
  securityEnabled: true
  securityProtocol: SASL_SSL
  saslMechanism: SCRAM-SHA-256
  acks: all
  sleepTimeMs: 50
  consumerGroupId: test-group